- name: Direct Sonarr to Search for Wanted Items
  hosts: all
  tasks:
  - name: Search for all wanted items in Sonarr
    uri:
      url: "{{ sonarr_server }}/api/command"
      method: POST
      body_format: json
      body:
        name: "command"
        seasonIds: []
        episodeIds: []
        name: "MissingEpisodeSearch"
    headers:
      Content-Type: "application/json"
      X-Api-Key: "{{ sonarr_api_key }}"
    register: result

  - name: Debug Sonarr API response
    debug:
      var: result
