- name: Direct Sonarr to Search for Wanted Items
  hosts: localhost
  tasks:
  - name: Search for all wanted items in Sonarr
    uri:
      url: "{{ sonarr_server }}/api/command"
      method: POST
      body_format: json
      body:
        name: "command"
        seasonIds: []
        episodeIds: []
        name: "MissingEpisodeSearch"
      headers:
        Content-Type: "application/json"
        X-Api-Key: "{{ sonarr_api_key }}"
      user: "{{ sonarr_username }}"
      password: "{{ sonarr_password }}"
      force_basic_auth: yes
    register: result

  - name: Debug Sonarr API response
    debug:
      var: result
